In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2018"
df1 = pd.read_html(link)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [3]:
df1

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2]
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3]
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4]
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5]
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6]
...,...,...,...,...,...,...
69,MARCH,29,Ready Player One,Warner Bros. Pictures / Village Roadshow Pictu...,"Steven Spielberg (director); Ernest Cline, Zak...",[71]
70,MARCH,30,Tyler Perry's Acrimony,Lionsgate / Tyler Perry Films,Tyler Perry (director/screenplay); Taraji P. H...,[72]
71,MARCH,30,God's Not Dead: A Light in Darkness,Pure Flix,Michael Mason (director/screenplay); David A. ...,[73]
72,MARCH,30,Gemini,Neon,"Aaron Katz (director/screenplay); Lola Kirke, ...",[74]
73,MARCH,30,The Last Movie Star,A24,Adam Rifkin (director/screenplay); Burt Reynol...,[75]

In [4]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [5]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,Ref.
0,JANUARY,5,Insidious: The Last Key,Universal Pictures / Blumhouse Productions / S...,Adam Robitel (director); Leigh Whannell (scree...,[2]
1,JANUARY,5,The Strange Ones,Vertical Entertainment,Lauren Wolkstein (director); Christopher Radcl...,[3]
2,JANUARY,5,Stratton,Momentum Pictures,"Simon West (director); Duncan Falconer, Warren...",[4]
3,JANUARY,10,Sweet Country,Samuel Goldwyn Films,"Warwick Thornton (director); David Tranter, St...",[5]
4,JANUARY,12,The Commuter,Lionsgate / StudioCanal / The Picture Company,Jaume Collet-Serra (director); Byron Willinger...,[6]
...,...,...,...,...,...,...
264,DECEMBER,25,Holmes & Watson,Columbia Pictures / Gary Sanchez Productions,Etan Cohen (director/screenplay); Will Ferrell...,[163]
265,DECEMBER,25,Vice,Annapurna Pictures / Plan B Entertainment,Adam McKay (director/screenplay); Christian Ba...,[137]
266,DECEMBER,25,On the Basis of Sex,Focus Features,Mimi Leder (director); Daniel Stiepleman (scre...,[226]
267,DECEMBER,25,Destroyer,Annapurna Pictures,"Karyn Kusama (director); Phil Hay, Matt Manfre...",[258]
268,DECEMBER,28,Black Mirror: Bandersnatch,Netflix,David Slade (director); Charlie Brooker (scree...,[259]

In [22]:
pip install tmdbv3api

Collecting tmdbv3api
  Downloading tmdbv3api-1.7.5-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (from tmdbv3api) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests->tmdbv3api) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\hp\anaconda3\lib\site-packages (from requests->tmdbv3api) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests->tmdbv3api) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests->tmdbv3api) (2020.12.5)
Installing collected packages: tmdbv3api
Successfully installed tmdbv3api-1.7.5
Note: you may need to restart the kernel to use updated packages.

In [14]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '76daa7075f7dc2e4a339f93d8f71288d'

In [29]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    movie_id = result[0].id
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
    data_json = response.json()
    if data_json['genres']:
        genre_str = " " 
        for i in range(0,len(data_json['genres'])):
            genres.append(data_json['genres'][i]['name'])
        return genre_str.join(genres)
    else:
        np.NaN

In [30]:
get_genre(str(df['Title'][0]))

'Horror Mystery Thriller'

In [31]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

In [35]:
df = df[['Title','Cast and crew','genres']]

In [36]:
df.head()

,Title,Cast and crew,genres
0,Insidious: The Last Key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller
1,The Strange Ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama
2,Stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller
3,Sweet Country,"Warwick Thornton (director); David Tranter, St...",Drama History Western
4,The Commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller

In [61]:
df['Cast and crew'][0]

'Adam Robitel (director); Leigh Whannell (screenplay); Lin Shaye, Angus Sampson, Leigh Whannell, Spencer Locke, Caitlin Gerard, Kirk Acevedo, Bruce Davison'

In [48]:
df['Cast and crew'][0].split("(director)")[0].strip()

'Adam Robitel'

In [53]:
def drget(x):
    if "(director)" in x:
        return x.split("(director)")[0].strip()
    elif "(director/screenplay)" in x:
        return x.split("(director/screenplay)")[0].strip()
    else:
        return x.split(" (director/screenplay)")[0].strip()

In [54]:
df["director_name"] = df['Cast and crew'].map(lambda x : drget(x))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [55]:
df["director_name"]

0            Adam Robitel
1        Lauren Wolkstein
2              Simon West
3        Warwick Thornton
4      Jaume Collet-Serra
              ...
264            Etan Cohen
265            Adam McKay
266            Mimi Leder
267          Karyn Kusama
268           David Slade
Name: director_name, Length: 269, dtype: object

In [62]:
df['Cast and crew'][0].replace(";",",").split(",")

['Adam Robitel (director)',
 ' Leigh Whannell (screenplay)',
 ' Lin Shaye',
 ' Angus Sampson',
 ' Leigh Whannell',
 ' Spencer Locke',
 ' Caitlin Gerard',
 ' Kirk Acevedo',
 ' Bruce Davison']

In [66]:
df['Cast and crew'][0].split("(screenplay);")

['Adam Robitel (director); Leigh Whannell ',
 ' Lin Shaye, Angus Sampson, Leigh Whannell, Spencer Locke, Caitlin Gerard, Kirk Acevedo, Bruce Davison']

In [83]:
def screenplaying(x):
    c = 0
    if "(screenplay)" in x:
        c+=1
    elif "(co-director/screenplay)" in x:
        c+=1
    elif "(director/screenplay)":
        c+=1
    return c

In [84]:
df['Cast and crew'].map(lambda x : screenplaying(x))

0      1
1      1
2      1
3      1
4      1
      ..
264    1
265    1
266    1
267    1
268    1
Name: Cast and crew, Length: 269, dtype: int64

In [81]:
df['Cast and crew'][1].split("(screenplay);")

['Lauren Wolkstein (director); Christopher Radcliff (co-director/screenplay); Alex Pettyfer, James Freedson-Jackson, Emily Althaus, Gene Jones, Owen Campbell, Tobias Campbell']

In [94]:
def get_actor(x,num):
    try:
        if "(screenplay); " in x:
            return ((x.split("screenplay); ")[-1]).split(", ")[num])
        elif "(co-director/screenplay);" in x:
            return ((x.split("co-director/screenplay); ")[-1]).split(", ")[num])
        elif "(director/screenplay);" in x:
            return ((x.split("director/screenplay); ")[-1]).split(", ")[num])
    except:
        return np.nan

In [95]:
df['actor_1_name'] = df['Cast and crew'].map(lambda x: get_actor(x,0))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [96]:
df['actor_2_name'] = df['Cast and crew'].map(lambda x: get_actor(x,1))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [99]:
df['actor_3_name'] = df['Cast and crew'].map(lambda x: get_actor(x,2))

In [103]:
df.Title = df.Title.str.lower()

In [104]:
df.head()

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,insidious: the last key,Adam Robitel (director); Leigh Whannell (scree...,Horror Mystery Thriller,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell
1,the strange ones,Lauren Wolkstein (director); Christopher Radcl...,Thriller Drama,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus
2,stratton,"Simon West (director); Duncan Falconer, Warren...",Action Thriller,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan
3,sweet country,"Warwick Thornton (director); David Tranter, St...",Drama History Western,Warwick Thornton,Bryan Brown,Sam Neill,NaN
4,the commuter,Jaume Collet-Serra (director); Byron Willinger...,Action Thriller,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson

In [107]:
df = df.drop(['Cast and crew'], axis = 1)

In [109]:
df = df.rename(columns={"Title" : "movie_title"})

In [118]:
df['actor_2_name'] = df['actor_2_name'].replace(np.nan, 'unknown')
df['actor_3_name'] = df['actor_3_name'].replace(np.nan, 'unknown')
df['actor_1_name'] = df['actor_1_name'].replace(np.nan, 'unknown')
df['genres'] = df['genres'].replace(np.nan,'unknown')

In [119]:
df.isna().sum()

movie_title      0
genres           0
director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
dtype: int64

In [141]:
df['comb'] = df['actor_1_name'] + ' ' + df['actor_2_name'] + ' '+ df['actor_3_name'] + ' '+ df['director_name'] +' ' + df['genres']

In [142]:
df.head()

,movie_title,genres,director_name,actor_1_name,actor_2_name,actor_3_name,comb
0,insidious: the last key,Horror Mystery Thriller,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,the strange ones,Thriller Drama,Lauren Wolkstein,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Alex Pettyfer James Freedson-Jackson Emily Alt...
2,stratton,Action Thriller,Simon West,Dominic Cooper,Austin Stowell,Gemma Chan,Dominic Cooper Austin Stowell Gemma Chan Simon...
3,sweet country,Drama History Western,Warwick Thornton,Bryan Brown,Sam Neill,unknown,Bryan Brown Sam Neill unknown Warwick Thornton...
4,the commuter,Action Thriller,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...

In [144]:
d17 = pd.read_csv("Data2017.csv")
d17.head()

,Unnamed: 0,director_name,actor_1_name,actor_2_name,actor_3_name,movie_title,genres,comb
0,0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,avatar,Action Adventure Fantasy Sci-Fi,James CameronCCH PounderJoel David MooreWes St...
1,1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,pirates of the caribbean: at world's end,Action Adventure Fantasy,Gore VerbinskiJohnny DeppOrlando BloomJack Dav...
2,2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,spectre,Action Adventure Thriller,Sam MendesChristoph WaltzRory KinnearStephanie...
3,3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,the dark knight rises,Action Thriller,Christopher NolanTom HardyChristian BaleJoseph...
4,4,Doug Walker,Doug Walker,Rob Walker,unknow,star wars: episode vii - the force awakensÂ ...,Documentary,Doug WalkerDoug WalkerRob WalkerunknowDocument...

In [145]:
d17 = d17.iloc[:,0:]
d17.head()

,Unnamed: 0,director_name,actor_1_name,actor_2_name,actor_3_name,movie_title,genres,comb
0,0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,avatar,Action Adventure Fantasy Sci-Fi,James CameronCCH PounderJoel David MooreWes St...
1,1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,pirates of the caribbean: at world's end,Action Adventure Fantasy,Gore VerbinskiJohnny DeppOrlando BloomJack Dav...
2,2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,spectre,Action Adventure Thriller,Sam MendesChristoph WaltzRory KinnearStephanie...
3,3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,the dark knight rises,Action Thriller,Christopher NolanTom HardyChristian BaleJoseph...
4,4,Doug Walker,Doug Walker,Rob Walker,unknow,star wars: episode vii - the force awakensÂ ...,Documentary,Doug WalkerDoug WalkerRob WalkerunknowDocument...

In [146]:
d17['comb'] = d17['actor_1_name'] + ' ' + d17['actor_2_name'] + ' '+ d17['actor_3_name'] + ' '+ d17['director_name'] +' ' + d17['genres']

In [147]:
d17.head()

,Unnamed: 0,director_name,actor_1_name,actor_2_name,actor_3_name,movie_title,genres,comb
0,0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,avatar,Action Adventure Fantasy Sci-Fi,CCH Pounder Joel David Moore Wes Studi James C...
1,1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,pirates of the caribbean: at world's end,Action Adventure Fantasy,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,spectre,Action Adventure Thriller,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,the dark knight rises,Action Thriller,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,4,Doug Walker,Doug Walker,Rob Walker,unknow,star wars: episode vii - the force awakensÂ ...,Documentary,Doug Walker Rob Walker unknow Doug Walker Docu...

In [155]:
data18 = d17.append(df,ignore_index=True,sort=False)

In [156]:
data18

,Unnamed: 0,director_name,actor_1_name,actor_2_name,actor_3_name,movie_title,genres,comb
0,0.0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,avatar,Action Adventure Fantasy Sci-Fi,CCH Pounder Joel David Moore Wes Studi James C...
1,1.0,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,pirates of the caribbean: at world's end,Action Adventure Fantasy,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,2.0,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,spectre,Action Adventure Thriller,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,3.0,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,the dark knight rises,Action Thriller,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,4.0,Doug Walker,Doug Walker,Rob Walker,unknow,star wars: episode vii - the force awakensÂ ...,Documentary,Doug Walker Rob Walker unknow Doug Walker Docu...
...,...,...,...,...,...,...,...,...
5634,NaN,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,holmes & watson,Mystery Adventure Comedy Crime,Will Ferrell John C. Reilly Rebecca Hall Etan ...
5635,NaN,Adam McKay,Christian Bale,Amy Adams,Steve Carell,vice,Thriller Science Fiction Action Adventure,Christian Bale Amy Adams Steve Carell Adam McK...
5636,NaN,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,on the basis of sex,Drama History,Felicity Jones Armie Hammer Justin Theroux Mim...
5637,NaN,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,destroyer,Thriller Crime Drama Action,Nicole Kidman Sebastian Stan Toby Kebbell Kary...
5638,NaN,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,black mirror: bandersnatch,Science Fiction Mystery Drama Thriller TV Movie,Fionn Whitehead Will Poulter Asim Chaudhry Dav...

In [162]:
data18.columns

Index(['Unnamed: 0', 'director_name', 'actor_1_name', 'actor_2_name',
       'actor_3_name', 'movie_title', 'genres', 'comb'],
      dtype='object')

In [ ]:
data18 = data18.drop(['Unnamed: 0'],axis=1)

In [166]:
data18

,director_name,actor_1_name,actor_2_name,actor_3_name,movie_title,genres,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,avatar,Action Adventure Fantasy Sci-Fi,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,pirates of the caribbean: at world's end,Action Adventure Fantasy,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,spectre,Action Adventure Thriller,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,the dark knight rises,Action Thriller,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknow,star wars: episode vii - the force awakensÂ ...,Documentary,Doug Walker Rob Walker unknow Doug Walker Docu...
...,...,...,...,...,...,...,...
5634,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,holmes & watson,Mystery Adventure Comedy Crime,Will Ferrell John C. Reilly Rebecca Hall Etan ...
5635,Adam McKay,Christian Bale,Amy Adams,Steve Carell,vice,Thriller Science Fiction Action Adventure,Christian Bale Amy Adams Steve Carell Adam McK...
5636,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,on the basis of sex,Drama History,Felicity Jones Armie Hammer Justin Theroux Mim...
5637,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,destroyer,Thriller Crime Drama Action,Nicole Kidman Sebastian Stan Toby Kebbell Kary...
5638,David Slade,Fionn Whitehead,Will Poulter,Asim Chaudhry,black mirror: bandersnatch,Science Fiction Mystery Drama Thriller TV Movie,Fionn Whitehead Will Poulter Asim Chaudhry Dav...